---
- name: Deploy Podman Container from ACR
  hosts: all
  become: true
  tasks:
    - name: Update package list
      apt:
        update_cache: yes
        cache_valid_time: 3600  # Optional: Cache validity in seconds (e.g., 1 hour)

    - name: Install dependencies
      apt:
        name:
          - software-properties-common
        state: present

    - name: Add Podman repository
      apt_repository:
        repo: ppa:projectatomic/ppa
        state: present

    - name: Update package list after adding repo
      apt:
        update_cache: yes

    - name: Install Podman
      apt:
        name: podman
        state: present

    - name: Verify Podman version
      command: podman --version
      register: podman_version

    - name: Show podman version
      debug:
        msg: "Podman installed version is {{ podman_version.stdout }}"      

    - name: Login into ACR
      shell: |
        podman login cgbuniracr.azurecr.io -u cgbuniracr -p {{ lookup('env', 'ACR_PWD') }}

    - name: Pull image from Docker Hub
      command: >
        podman pull docker.io/carogarb/nginx-hello-world:latest
      become: yes

    - name: Tag image for ACR
      command: >
        podman tag docker.io/carogarb/nginx-hello-world:latest cgbuniracr.azurecr.io/nginx-hello-world:latest
      become: yes

    - name: Push image to ACR
      command: >
        podman push cgbuniracr.azurecr.io/nginx-hello-world:latest
      become: yes     
    
    - name: Run Podman container
      shell: |
        podman run -d -p 80:80 --name ngnix-container-cgb cgbuniracr.azurecr.io/nginx-hello-world:latest