---
- name: Deploy Podman Container from ACR
  hosts: azure-vm
  become: true
  tasks:
    - name: Install Podman
      apt:
        name: podman
        state: present
        update_cache: yes

    - name: Login into ACR
      shell: |
        podman login cgbuniracr.azurecr.io -u cgbuniracr -p {{ lookup('env', 'ACR_PWD') }}
        
    - name: Build image from Containerfile
      shell: |
        podman build -t ngnix-image-cgb ../podman
    
    - name: Run Podman container
      shell: |
        podman run -d -p 80:80 --name ngnix-container-cgb cgbuniracr.azurecr.io/ngnix-image-cgb:latest