---
- name: Store Terraform values from terraform_outputs.json file
  hosts: localhost
  become: true
  roles:
    - terraform
  vars_files:
      - ./vars.yml
        
- name: Deploy Podman Container from ACR
  hosts: azure-vm
  become: true
  roles:
    - acr
  vars_files:
      - ./vars.yml