---
- name: Install podman on VM
  hosts: azure-vm
  become: true
  roles:
    - vm
  vars_files:
      - ./vars.yml
        
- name: Pull, tag, push and run Podman Container
  hosts: azure-vm
  become: true
  roles:
    - acr
  vars_files:
      - ./vars.yml